version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mariem  # Remplacez par un mot de passe sécurisé
      MYSQL_DATABASE: db          # Nom de la base de données
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=caching_sha2_password
    volumes:
      - db_data:/var/lib/mysql          # Volume persistant pour MySQL
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro  # Fixe les fuseaux horaires

  app-events:
    depends_on:
      - mysqldb
    image: djelassimariem/event:latest  # Remplacez par le nom correct de l'image Docker
    container_name: app-events
    restart: on-failure
    ports:
      - "8089:8089"  # Port exposé pour l'application Spring Boot
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "mariem"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
